// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace webcrud.Entities
{
    public partial class UserRestriction
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public int? RestrictionId { get; set; }

        public virtual Restriction Restriction { get; set; }
        public virtual User User { get; set; }
    }
}